-- ==============================================================================
-- SQL PARA ZERAR E CRIAR AS TABELAS CORRETAS DO SISTEMA
-- Instruções:
-- 1. Acesse seu painel do Supabase -> SQL Editor -> New Query
-- 2. Cole este código inteiro lá e clique em "Run"
-- ==============================================================================

-- 1. Apaga as tabelas antigas para evitar conflitos de colunas
DROP TABLE IF EXISTS public.noticias CASCADE;
DROP TABLE IF EXISTS public.programacao CASCADE;
DROP TABLE IF EXISTS public.locutores CASCADE;
DROP TABLE IF EXISTS public.patrocinadores CASCADE;
DROP TABLE IF EXISTS public.configuracoes CASCADE;

-- 2. Criação da tabela: noticias
CREATE TABLE public.noticias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  resumo TEXT,
  textocompleto TEXT,
  categoria TEXT,
  imagem TEXT,
  data TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);  

-- 3. Criação da tabela: programacao
CREATE TABLE public.programacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  horario TEXT,
  locutor TEXT,
  ordem INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Criação da tabela: locutores
CREATE TABLE public.locutores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cargo TEXT,
  bio TEXT,
  foto TEXT,
  ordem INTEGER,
  instagram TEXT,
  whatsapp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Criação da tabela: patrocinadores
CREATE TABLE public.patrocinadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  logo TEXT,
  link TEXT,
  ordem INTEGER,
  cnpj TEXT,
  "diaPagamento" TEXT,
  renovacao TEXT,
  "valorPago" TEXT,
  status TEXT DEFAULT 'ativo',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Criação da tabela: configuracoes (Para Ads e Live Stream)
CREATE TABLE public.configuracoes (
  chave TEXT PRIMARY KEY,
  valor TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
