-- ==============================================================================
-- SCHEMA SQL PARA SUPABASE - RÁDIO PULSO FM
-- Instruções:
-- 1. Acesse seu painel do Supabase
-- 2. Vá em "SQL Editor"
-- 3. Cole este código inteiro lá e clique em "Run"
-- ==============================================================================

-- 1. TABELA: noticias
CREATE TABLE public.noticias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  resumo TEXT,
  textoCompleto TEXT,
  categoria TEXT,
  imagem TEXT,
  data TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA: programacao
CREATE TABLE public.programacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  horario TEXT,
  locutor TEXT,
  ordem INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA: locutores
CREATE TABLE public.locutores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cargo TEXT,
  bio TEXT,
  foto TEXT,
  ordem INTEGER,
  instagram TEXT,
  whatsapp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA: patrocinadores
CREATE TABLE public.patrocinadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  logo TEXT,
  link TEXT,
  ordem INTEGER,
  cnpj TEXT,
  "diaPagamento" TEXT,
  renovacao TEXT,
  "valorPago" TEXT,
  status TEXT DEFAULT 'ativo',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABELA: configuracoes (Para Ads e Live Stream)
CREATE TABLE public.configuracoes (
  chave TEXT PRIMARY KEY,
  valor TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- BUCKET DE STORAGE E SUAS POLÍTICAS (Executar no SQL Editor)
-- Para que o painel admin consiga enviar e ler as imagens usando a chave pública:
-- ==============================================================================

-- 1. Se você ainda não criou o bucket, vá em "Storage" -> "New Bucket" e crie um chamado: "uploads" (marque como Public)
-- 2. Copie e cole os comandos de política abaixo no SQL Editor do Supabase e clique em "Run":

CREATE POLICY "Permitir leitura publica de uploads" ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'uploads');

CREATE POLICY "Permitir upload publico de uploads" ON storage.objects
  FOR INSERT TO public WITH CHECK (bucket_id = 'uploads');

CREATE POLICY "Permitir atualizacao publica de uploads" ON storage.objects
  FOR UPDATE TO public USING (bucket_id = 'uploads');

CREATE POLICY "Permitir delecao publica de uploads" ON storage.objects
  FOR DELETE TO public USING (bucket_id = 'uploads');
